services:

 db:
  image: postgres
  environment:
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=pass
  ports:
   - "5432:5432"
  volumes: 
   - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

   
 server:
  build: server/.
  ports:
   - "8000:8000"
  links:
   - "db"
   - "excel_mock"
  depends_on:
   - db
   - excel_mock
  
 excel_mock:
  build: mock_excel_api/.
  ports:
   - "8080:8080"
